name: Particle-AddOn
main: iTzFreeHD\PC\Particle
api:
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA12
version: 1.0.5-BETA§8-§bby Hyroxing-Development=>iTzFreeHD§a
commands:
  freeparticle:
    description: /freeparticle